name: flutter_projects
description: Flutter apps with amazing design and moderate animations
version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.1
  google_fonts: ^4.0.4
  flutter_vector_icons: ^1.0.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^1.1.1+1
  vector_math: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.3
flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/findout/
    - assets/img/streaming/
    - assets/img/movie/
    - assets/img/music/
    - assets/img/superheroes/
    - assets/img/instagram/
    - assets/img/gaming/
    - assets/svg/instagram/
    - assets/svg/medical/
    - assets/svg/streaming/
    - assets/img/books/
    - assets/img/projects/
    - assets/img/boats/
  fonts:
    - family: MDIcons
      fonts:
        - asset: assets/icons/md_icons/MdIcons.ttf

flutter_icons:
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"